language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
    allow_failures:
        - php:
          - hhvm
          - 5.6

install: composer install
script:
  - phpunit --configuration tests/FullTests.xml --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 src/

after_script: php vendor/bin/coveralls